#!/bin/bash
#PBS -l walltime=48:00:00
#PBS -l nodes=1:ppn=8
#PBS -l pmem=200mb
#PBS -m abe
#PBS -M subhomoymahajan@gmail.com
filename="1AKI"
cd $PBS_O_WORKDIR
ls
#Load the gromacs
module load gromacs/5.1.3
#convert the pdb file to gromacs file, mention the forcefield to be used and the water model
gmx pdb2gmx -f $filename".pdb" -o $filename"_processed.gro" -water spce < ff.txt
echo "pdb file processed"
#defining the box of the system, both the shape and dimension around the protein
gmx editconf -f $filename"_processed.gro" -o $filename"_newbox.gro" -c -d 1.0 -bt cubic
echo "box created"
#Filling the box with water
gmx solvate -cp $filename"_newbox.gro" -cs spc216.gro -o $filename"_solv.gro" -p topol.top
echo "box solvated"
#adding ions to make the solution nuetral
gmx grompp -f ions.mdp -c $filename"_solv.gro" -p topol.top -o ions.tpr

## find the value of neg and pos using scripting
q=$(grep " qtot" topol.top | tail -n 1 | awk '{print $NF}')
echo "q = $q"
if [ $q -gt 0 ]
then 
    gmx genion -s ions.tpr -o $filename"_solv_ions.gro" -p topol.top -pname NA -nname CL -nn $q < sol.txt
    echo "ions added"
fi

if [$q -lt 0 ]
then
    q=`expr $q \* -1`
    gmx genion -s ions.tpr -o $filename"_solv_ions.gro" -p topol.top -pname NA -nname CL -np $q
    echo "ions added"
fi

#Energy Minimization
gmx grompp -f minim.mdp -c $filename"_solv_ions.gro" -p topol.top -o em.tpr
gmx_mpi mdrun -v -deffnm em
echo "Energy minization done"
#Generate potentital energy graph
gmx energy -f em.edr -o potential.xvg < pot.txt #how to choose using scripting

#NVT ensemble
gmx grompp -f nvt.mdp -c em.gro -p topol.top -o nvt.tpr
gmx_mpi mdrun -deffnm nvt
echo " NVT done"
#generate temperature profile
gmx energy -f nvt.edr -o temperature.xvg < temp.txt

#NPT ensemble
gmx grompp -f npt.mdp -c nvt.gro -t nvt.cpt -p topol.top -o npt.tpr
gmx_mpi mdrun -deffnm npt
#generate the pressure and density graph
gmx energy -f npt.edr -o pressure.xvg < pres.txt
gmx energy -f npt.edr -o density.xvg < dens.txt

#Production MD
gmx grompp -f md.mdp -c npt.gro -t npt.cpt -p topol.top -o md_0_1.tpr
gmx_mpi mdrun -deffnm md_0_1


#POST MD ANALYSIS
gmx trjconv -s md_0_1.tpr -f md_0_1.xtc -o md_0_1_noPBC.xtc -pbc mol -ur compact
#RMSD
gmx rms -s md_0_.tpr -f md_0_1_noPBC.xtc -o rmsd.xvg -tu ns < rms.txt
gmx rms -s em.tpr -f md_0_1_noPBC.xtc -o rmsd_xtal.xvg -tu ns < rms.txt
#Radius of gyration
gmx gyrate -s md_0_1.tpr -f md_0_1_noPBC.xtc -o gyrate.xvg  


